config/routes.rb
Rails.application.routes.draw do
  root 'rsvps#new'
  resources :rsvps, only: [:index, :new, :create, :destroy] do
    collection do
      get 'thankyou'
      get 'search'
    end
  end
  devise_for :users,
             :path => '',
             :path_names => { :sign_in => 'login', :sign_up => 'signup', :sign_out => 'logout' }

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  attr_accessor :rsvp_code

  searchkick

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :party, presence: true, length: { minimum: 5 }
  validates :attendees, presence: true
  #validates :accept, presence: true
  validates :comment, length: { minimum: 5 }, allow_blank: true
  validates :email, format: { with: VALID_EMAIL_REGEX }, allow_blank: true
  validates :rsvp_code, presence: true
  validate :valid_code

  #default_scope -> { order('lower(party) asc') }

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |attendee|
        csv << attendee.attributes.values_at(*column_names)
      end
    end
  end

  private

  def valid_code
    if rsvp_code.upcase != ENV['RSVP_CODE']
      errors.add(:rsvp_code, 'does not match invitation code')
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create, :thankyou, :search]
  #before_action :set_rsvp, only: [:destroy]
  helper_method :sort_column, :sort_direction

  def index
    @rsvps = Rsvp.order(sort_column + ' ' + sort_direction)
    @rsvps_paginate = @rsvps.paginate(page: params[:page], per_page: 15)
    @attendees_sum = @rsvps.where(accept: true).sum(:attendees)

    respond_to do |format|
      format.html
      format.csv { render text: @rsvps.to_csv }
    end
  end

  def new
    @rsvp = Rsvp.new
  end

  def create
    @rsvp = Rsvp.new(rsvp_params)

    #if verify_recaptcha(model: @rsvp) && @rsvp.save  #Uncomment to use reCAPTCHA
    if @rsvp.save                                     #Comment to use reCAPTCHA
      flash[:success] = 'Thank you for taking the time to fill this RSVP!'
      redirect_to thankyou_rsvps_path
    else
      render 'new'
    end
  end

  def destroy
    Rsvp.find(params[:id]).destroy
    flash[:success] = 'RSVP was successfully deleted.'
    redirect_to rsvps_path
  end

  def thankyou
  end

  def search
    if params[:search].present?
      @rsvps = Rsvp.search params[:search], fields: [:party], page: params[:page], per_page: 15

      @rsvps_count = @rsvps.total_count
    else
      @rsvps = Rsvp.paginate(page: params[:page], per_page: 15)
    end
  end

  private

  def rsvp_params
    params.require(:rsvp).permit(:party, :attendees, :email, :comment, :accept, :rsvp_code)
  end

  def sort_column
    Rsvp.column_names.include?(params[:sort]) ? params[:sort] : 'party'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  #def set_rsvp
  #  @rsvp = Rsvp.find(params[:id])
  #end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def human_boolean(boolean)
    boolean ? 'Yes' : 'No'
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

=begin
  def sortable_search(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:utf8 => '✓', :search => params[:search], :sort => column, :direction => direction}, {:class => css_class}
  end
=end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Andrea & Esau's Wedding</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Google Fonts embed code -->
  <script type="text/javascript">
    (function() {
      var link_element = document.createElement("link"),
          s = document.getElementsByTagName("script")[0];
      if (window.location.protocol !== "http:" && window.location.protocol !== "https:") {
        link_element.href = "http:";
      }
      link_element.href += "//fonts.googleapis.com/css?family=Stalemate:400";
      link_element.rel = "stylesheet";
      link_element.type = "text/css";
      s.parentNode.insertBefore(link_element, s);
    })();
  </script>
  <script type="text/javascript">
    (function() {
      var link_element = document.createElement("link"),
          s = document.getElementsByTagName("script")[0];
      if (window.location.protocol !== "http:" && window.location.protocol !== "https:") {
        link_element.href = "http:";
      }
      link_element.href += "//fonts.googleapis.com/css?family=Playball:400";
      link_element.rel = "stylesheet";
      link_element.type = "text/css";
      s.parentNode.insertBefore(link_element, s);
    })();
  </script>
  <!-- End Google Fonts embed code -->

</head>
<body>
  <% if user_signed_in? %>
    <%= render 'shared/menu' %>
  <% end %>

  <div class='container'>
    <h1 class="text-center">Andrea & Esau's Wedding</h1>
    <hr />
    <div class="main-body">
      <%= render 'shared/messages' %>
      <%= yield %>
    </div>
  </div>

  <%#= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/rsvps/_guestlist.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>
      <%= sortable 'party', 'Name' %>
    </th>
    <th>
      <%= sortable 'attendees', 'Number of Attendees' %>
    </th>
    <th>
      <%= sortable 'accept', 'Accept' %>
    </th>
    <th>
      Comment
    </th>
    <th>
      Email
    </th>
    <th>
      <%= sortable 'created_at', 'Date' %>
    </th>
    <th>
      Action
    </th>
  </tr>
  </thead>
  <tbody>
  <% obj.each do |r| %>
    <tr>
      <td>
        <%= r.party %>
      </td>
      <td>
        <%= r.attendees %>
      </td>
      <td>
        <%= human_boolean(r.accept) %>
      </td>
      <td>
        <%= simple_format(r.comment) %>
      </td>
      <td>
        <%= r.email %>
      </td>
      <td>
        <%= r.created_at.strftime("%b %d %Y") %>
      </td>
      <td>
        <%= link_to 'Delete', r, method: :delete, class: 'btn btn-danger btn-xs',
                    data: { confirm: 'Are you sure you want to delete this RSVP?' } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/rsvps/index.html.erb
<div class="center-box guest-list">
  <h2 class="text-center">Guest List</h2>
  <p><strong>Total number of attendees</strong>: <%= @attendees_sum %></p>

  <%= render 'guestlist', obj: @rsvps_paginate %>

  <div class="row">
    <div class="col-md-9">
      <%= will_paginate @rsvps_paginate %>
    </div>
    <div class="col-md-3">
      <%= link_to 'Download Guest List', rsvps_path(format: 'csv'), class: 'btn btn-default btn-guest-list' %>
    </div>
  </div>

</div>

app/views/rsvps/new.html.erb
<div class="center-box">
  <!--<p class="text-center">Kindly respond by May 16<sup>th</sup>, 2016</p>-->

  <%= render 'shared/errors', obj: @rsvp %>

  <%= form_for(@rsvp, :html => { class: 'form-horizontal', role: 'form' }) do |r| %>

    <div class="form-group">
      <div class="control-label pull-left">
        <%= r.label :party, 'Name' %> <span class="required">*</span>
      </div>
      <div class="control-label">
        <%= r.text_field :party, class: 'form-control', placeholder: 'Individual or family name', autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label pull-left">
        <%= r.label :attendees, 'Number of attendees' %> <span class="required">*</span>
      </div>
      <div class="control-label">
        <%= r.number_field :attendees, class: 'form-control', placeholder: 'Enter 0 (Zero) if not attending' %>
      </div>
    </div>

    <div class="form-group">
      <%= r.radio_button :accept, true, :checked => true %>
      <%= r.label :accept, 'Accepts with Pleasure' %>
      &nbsp;&nbsp;&nbsp;
      <%= r.radio_button :accept, false, :checked => false %>
      <%= r.label :accept, 'Declines with Regrets' %>
    </div>

    <div class="form-group">
      <div class="control-label pull-left">
        <%= r.label :email %>
      </div>
      <div class="control-label">
        <%= r.text_field :email, class: 'form-control' %>
        <small class="pull-left">We will only email you once a few days before the wedding</small>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label pull-left">
        <%= r.label :comment %>
      </div>
      <div class="control-label">
        <%= r.text_area :comment, rows: 4, class: 'form-control', placeholder: 'Leave us a comment' %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label pull-left">
        <label for="rsvp_code">Enter code found in invitation</label> <span class="required">*</span>
      </div>
      <div class="control-label">
        <%= r.text_field :rsvp_code, class: 'form-control' %>
      </div>
    </div>

    <div class="text-center">
      <%#Uncomment for reCAPTCHA= recaptcha_tags %>
    </div>

    <div class='form-group'>
      <div class='control-label pull-left'>
        <%= r.submit 'RSVP', class: 'btn btn-primary btn-lg' %>
      </div>
    </div>

  <% end %>

  <p class="required"><small>* Required fields</small></p>
</div>

app/views/rsvps/search.html.erb
<div class="center-box guest-list">
  <h2 class="text-center">Search Results</h2>
  <p><%= @rsvps_count %> search result(s)</p>

  <%= render 'guestlist', obj: @rsvps %>

  <div class="row">
    <div class="col-md-9">
      <%= will_paginate %>
    </div>
    <div class="col-md-3">

    </div>
  </div>

</div>

app/views/rsvps/thankyou.html.erb
<div class="center-box thank-you">
  <h2 class="text-center">A Little Bit About Our Story</h2>
  <p>The physical details of our story start in Colorado Springs in August of 2014, however we know that God was
    at work long before then to bring us to the point of meeting each other.</p>
  <p><i>Boundless</i>, the online community and subdivision of Focus on the Family for young adults, was planning
    the very first ever Pursuit conference for Christian singles around the world to participate in a weekend of
    teaching, worship, mingling, and being challenged to live life with purpose. An event like this one, drawing
    hundreds of people from all walks of life and multiple countries around the world, started years in advance with
    prayer and took months to prepare.</p>
  <p>We both decided to attend and were excited for an opportunity to learn more from the speakers at the
    conference, but did not plan to have an even more meaningful experience while we were there. On the morning of
    the second day, Andrea was getting coffee before the first session began. Esau caught her smile from across
    the room, and decided to go introduce himself to her. As the first session was getting ready to begin, Esau
    invited Andrea to sit with him at his table. The morning continued on and by lunchtime, we made our way through
    the crowd to get our food and picnic with the other attendees outside on the lawn. It was a beautiful, sunny
    day and we enjoyed our conversation as a group. Gradually those in our immediate area dispersed one-by-one
    until it was just the two of us continuing to talk. We saw a lot of each other as the weekend continued
    (Esau was very attentive to go where Andrea went), and by the end of the conference, Esau made it clear that
    he wanted to get to know Andrea better.  We parted ways (Esau to Texas and Andrea to Kansas), agreeing that we
    could communicate (as friends only) over facebook to get to know each other better, but Andrea didn’t see much
    going beyond that.</p>
  <p>About a month later, Esau expressed a desire to again get to know Andrea better and see if there could be
    something more beyond friendship. By this time we had both found we had a lot in common and enjoyed each other’s
    friendship, albeit only over written communication thus far. We decided that the first step in determining if
    there was something more would be for us to visit each other again in person, so Esau made plans to fly up to
    visit Andrea the following month in her hometown of Abilene. The first visit went amazingly well, and we both
    prayed about what to do next, and decided that a visit by Andrea to Esau’s city of McAllen would be a wise next
    step before any decisions were made for our possible future together. This visit, too, went well, and by this
    time and after much thought, prayer, discussion, and counsel, we both had peace about beginning a long-distance
    relationship with each other. And that began our dating relationship of just over a year, which has stretched
    us, challenged us, and grown us in many ways that we could not have foreseen in the beginning.</p>
  <p>On Christmas Eve 2015 (after much anticipation on Andrea’s part leading up to that day) Esau asked Andrea
    to marry him. We look forward to sharing our special day with you and celebrating how God brought us together
    in a seemingly unlikely way (as we know He is amazing at doing).</p>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='row'>
    <div clas='col-xs-8 col-xs-offset-2'>
      <div class='panel panel-danger normal-font'>
        <div class='panel-heading'>
          <strong><span class='panel-title'>
            <%= pluralize(obj.errors.count, 'error') %>
            prohibited this RSVP from being submitted:
          </span></strong>
          <div class='panel-body'>
            <ul>
              <% obj.errors.full_messages.each do |err| %>
                <li><%= err %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'RSVP', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Guest List', rsvps_path %></li>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
      </ul>
      <%= form_tag search_rsvps_path, method: :get, class: 'navbar-form navbar-left' do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search guest list' %>
        </div>
        <%= submit_tag 'Search', name: nil, class: 'btn btn-default' %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "#{current_user.email}", edit_user_registration_path %></li>
        <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_messages.html.erb
<div class='row'>
  <div class='col-xs-10 col-xs-offset-1'>
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}"%> '>
        <a href='#' class='close' data-dismiss='alert'>&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>